language: ruby
rvm:
- 2.6

os: linux
dist: bionic

before_install:
 - gem install bundler
 - git clone --branch=publish https://github.com/adrianba/blog-legalfear.com.git ./_site

before_script:
 - chmod +x ./_deploy/cibuild.sh
 - chmod +x ./_deploy/deploy.sh

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./_deploy/cibuild.sh

after_success:
 - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./_deploy/deploy.sh; fi'

# branch whitelist
branches:
  only:
  - main

cache:
  bundler: true
  directories:
  - .cache

before_cache:
  mkdir -p .cache && cp .jekyll-metadata .cache

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: "Mw1eQe93KOi5xt+5NZH5MeCZsx2MdMFRHD0dCRGyJ21V4n2K92kuxGmmxqSv/LKA9kTC4gURWXhhONYsOIpvVYiH5synjF/q5Wqdr4NW1VCEIqXB0JSqbqetRjxkGwd0DZl+4c+mfMUI0HxUbW6fJa5dwUyIdgeD91N6YCdgOMqD6XwkLjF4+tlLvEOiNkCvdPk7VKYfxiMNEOScTAo87PlUEClhWVZeYtkNfrNGreJ7izmypOJDtlKXWZTEZ/NSbMChFcmsavKY6eCt61bQpdMyFLjgg0ciGpHxZVlVqwV3Gew5jlkJ3d5kMetaGR39u3yWrjqNSkkQ9PnxMDTJ9smgxfxPRorf1hln7kY3HPUlyemgVHWilnj+pL5u81onxBWMy64hT1lYfXlnoiSOej9L8MnJmW1Wf5DpGazWeAi4K9noHl32oAVx/59L/Gu2r4itHsRKElkY1ef82L7MJbI9ix6PtN9m7Y8B/chJv0P+MhDHGoU+2vRF8YdiABqwNqL5gh8ACckBXp/EtNxQ2HTDvhawW9BijS9Uk478CmE33wSCqALnmYi5iaWoGruDUbm4dWvZKvcc2UZdxV1/uJ2BeY9EIo0ZHF3/YbN8geuk9x78cb6h2PeKttJ8IcApvnLH3BvWWQ50ijCatdNfcw1Lx7Bru1j+d0HlcnJx9lU="