# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: LegalFear.com
email: ade@legalfear.com
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts and scribbles about the law, technology, and public policy - don't be afraid!
copyright: >-
  &copy; 2020 Adrian Bateman.
disclaimer: >-
    Disclaimer: The posts on this site are provided AS IS with no warranties, and confer no rights.
    The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://legalfear.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/logos/LegalFearLogo.svg"
read_time: true
words_per_minute: 200
twitter_username: adrianba
github_username:  adrianba
footer_links:
  - title: LinkedIn
    url: http://www.linkedin.com/in/adrianba
    icon: fab fa-linkedin
  - title: Twitter
    url: https://twitter.com/adrianba
    icon: fab fa-twitter-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Build settings
theme: jekyll-theme-so-simple # https://github.com/mmistakes/so-simple-theme
skin: "/assets/css/skins/legal.css"
locale: en-US
search_full_content: true

google_fonts:
  - name: "Source Serif Pro"
    weights: "400,400i,700,700i"
  - name: "Old Standard TT"
    weights: "400,400i,700,700i"

google_analytics: "UA-48621303-5"
twitter:
  username: adrianba # site's Twitter username

author:
  name: Adrian Bateman
  twitter: adrianba
  picture: /assets/images/adrianba.jpg

  # Liquid
liquid:
  error_mode: strict

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Outputting
permalink: /:year/:month/:day/:title:output_ext
timezone: "America/Los_Angeles"
feed:
  path: atom.xml

# Conversion
markdown: kramdown

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Reading Files
include:
  - web.config
exclude:
  - .gitignore
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .travis.yml
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - log
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .gitattributes
